"""Reproduce every figure and number in the paper from results/*.

Usage::

    python paper/reproduce.py

Outputs:
    REPORT.md          — full leaderboard + plots markdown
    results/plots/     — PNG + SVG figures
    paper/tables.md    — LaTeX-ready tables
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running from repo root or paper/
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "src"))

from vlm_anomaly.analysis.aggregator import (
    category_heatmap,
    cost_accuracy_table,
    leaderboard,
)
from vlm_anomaly.analysis.report_generator import generate
from vlm_anomaly.logging import configure_logging

configure_logging(json_logs=False, log_level="WARNING")

RESULTS_DIR = ROOT / "results"
REPORT_PATH = ROOT / "REPORT.md"
TABLES_PATH = ROOT / "paper" / "tables.md"


def main() -> None:
    print(f"Results dir : {RESULTS_DIR}")
    lb = leaderboard(RESULTS_DIR)

    if lb.empty:
        print("No results found in results/. Run an evaluation first.")
        print("  Quick mock run: python scripts/run_vlm_eval.py --backend mock "
              "--dataset mvtec --category bottle --limit 5")
        return

    print(f"Found {len(lb)} result rows across {lb['model_id'].nunique()} models.")

    # 1. Full report + plots
    print("\nGenerating REPORT.md and plots...")
    generate(RESULTS_DIR, REPORT_PATH)
    plots = list((RESULTS_DIR / "plots").glob("*.png"))
    print(f"  Written: {REPORT_PATH}")
    print(f"  Plots  : {[p.name for p in plots]}")

    # 2. Summary leaderboard (mean AUROC per model)
    cost_df = cost_accuracy_table(RESULTS_DIR)
    print("\nLeaderboard (mean AUROC across categories):")
    print(cost_df[["model_id", "mean_auroc", "mean_cost_per_image", "mean_latency_ms"]]
          .to_string(index=False))

    # 3. Per-category heatmap data
    pivot = category_heatmap(RESULTS_DIR)
    if not pivot.empty:
        print("\nAUROC heatmap (model × category):")
        print(pivot.round(3).to_string())

    # 4. Write LaTeX-ready tables
    _write_tables(lb, cost_df, pivot)
    print(f"\nTables: {TABLES_PATH}")
    print("\nDone.")


def _write_tables(lb, cost_df, pivot) -> None:
    lines = ["# Paper Tables\n", "_Auto-generated by paper/reproduce.py_\n"]

    # Table 1: leaderboard
    lines.append("## Table 1 — Leaderboard\n")
    if not lb.empty:
        lines.append(lb[["model_id", "backend", "dataset", "category",
                          "n_images", "auroc", "f1"]].to_markdown(index=False))
        lines.append("\n")

    # Table 2: cost-accuracy
    lines.append("## Table 2 — Cost vs Accuracy\n")
    if not cost_df.empty:
        lines.append(cost_df.to_markdown(index=False))
        lines.append("\n")

    # Table 3: category heatmap
    if not pivot.empty:
        lines.append("## Table 3 — AUROC by Model × Category\n")
        lines.append(pivot.round(3).to_markdown())
        lines.append("\n")

    TABLES_PATH.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
